site: make

# Site URL Configuration (critical for SEO)
url: "https://make.kaist.ac.kr"
baseurl: ""

# Site Metadata
title: "Make Lab - KAIST"
description: "HCI Research Lab at KAIST focusing on Haptics, VR, Digital Fabrication, Physical Computing, and Prototyping Tools"
keywords: "HCI, Human-Computer Interaction, KAIST, Haptics, VR, Virtual Reality, Digital Fabrication, Physical Computing, Prototyping, Interaction Design, Make Lab"

collections:
  pages:
    output: true
    permalink: /:name
  # posts:
  #   output: true
  #   permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: 'page'
  # - scope:
  #     path: ''
  #     type: 'posts'
  #   values:
  #     layout: 'post'
  - scope:
      path: ''
      type: 'projects'
    values:
      layout: 'project'

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: '/blog/page:num/'
