backend:
  name: git-gateway
  repo: makelab-kaist/makelab.github.io
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "news"
    label: "Lab News"
    files:
      - label: "News Items"
        name: "news"
        file: "_data/news.yaml"
        fields:
          - label: "Entries"
            name: "entries"
            widget: "list"
            fields:
              - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
              - { label: "Text", name: "text", widget: "markdown" }